insert into public.experiences (
  id, company, role_pt, role_en, period_pt, period_en, points_pt, points_en, status, sort_order,
  summary_pt, summary_en, description_pt, description_en, responsibilities_pt, responsibilities_en,
  start_date, end_date, current, location_pt, location_en, employment_type, technologies,
  display_order, featured, recruiter_visible, publication_status, published_at, archived_at
) values
  ('00000000-0000-4000-8000-000000000001', 'MARKTS', 'Desenvolvedor Full Stack Web & Mobile', 'Full Stack Web & Mobile Developer', 'Junho de 2025 - Atual', 'June 2025 - Present', '["Aplicações Web, Android e iOS entre múltiplos frontends e microserviços.", "React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ e Prisma.", "Mapas e análise geográfica com H3, deck.gl e Google Maps.", "Fluxos com regras de negócio, máquinas de estado e operação móvel sob conectividade instável."]'::jsonb, '["Web, Android and iOS applications across multiple frontends and microservices.", "React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ and Prisma.", "Maps and geographic analysis with H3, deck.gl and Google Maps.", "Business-rule flows, state machines and mobile operation under unreliable connectivity."]'::jsonb, 'published', 0, 'Aplicações Web, Android e iOS entre múltiplos frontends e microserviços.', 'Web, Android and iOS applications across multiple frontends and microservices.', 'Aplicações Web, Android e iOS entre múltiplos frontends e microserviços.', 'Web, Android and iOS applications across multiple frontends and microservices.', array['Aplicações Web, Android e iOS entre múltiplos frontends e microserviços.', 'React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ e Prisma.', 'Mapas e análise geográfica com H3, deck.gl e Google Maps.', 'Fluxos com regras de negócio, máquinas de estado e operação móvel sob conectividade instável.'], array['Web, Android and iOS applications across multiple frontends and microservices.', 'React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ and Prisma.', 'Maps and geographic analysis with H3, deck.gl and Google Maps.', 'Business-rule flows, state machines and mobile operation under unreliable connectivity.'], null, null, true, null, null, null, array['React', 'React Native', 'TypeScript', 'NestJS', 'REST', 'gRPC', 'Socket.IO', 'Redis', 'BullMQ', 'Prisma', 'H3', 'deck.gl', 'Google Maps'], 0, true, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000002', 'SALB - Indústria Cerealista', 'Desenvolvedor Full Stack', 'Full Stack Developer', 'Dezembro de 2024 - Maio de 2025', 'December 2024 - May 2025', '["Site institucional e catálogo de produtos.", "QR Codes em produtos, estoque, etiquetas e integrações de cadastro.", "Integração com roteirização de entregas usando Next.js, TypeScript, Prisma e PostgreSQL."]'::jsonb, '["Institutional website and product catalog.", "Product QR codes, inventory, labels and product-record integrations.", "Delivery-routing integration using Next.js, TypeScript, Prisma and PostgreSQL."]'::jsonb, 'published', 1, 'Site institucional e catálogo de produtos.', 'Institutional website and product catalog.', 'Site institucional e catálogo de produtos.', 'Institutional website and product catalog.', array['Site institucional e catálogo de produtos.', 'QR Codes em produtos, estoque, etiquetas e integrações de cadastro.', 'Integração com roteirização de entregas usando Next.js, TypeScript, Prisma e PostgreSQL.'], array['Institutional website and product catalog.', 'Product QR codes, inventory, labels and product-record integrations.', 'Delivery-routing integration using Next.js, TypeScript, Prisma and PostgreSQL.'], null, null, false, null, null, null, array['Next.js', 'TypeScript', 'Prisma', 'PostgreSQL'], 1, true, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000003', 'Lumis', 'Desenvolvedor Web/Java', 'Web/Java Developer', 'Junho de 2022 - Dezembro de 2023', 'June 2022 - December 2023', '["Desenvolvimento e sustentação de portais corporativos.", "Java, LumisXP, Hibernate, JavaScript, HTML, CSS e XSL.", "Componentes, formulários, integrações e regras de negócio para equipes multidisciplinares."]'::jsonb, '["Development and maintenance of corporate portals.", "Java, LumisXP, Hibernate, JavaScript, HTML, CSS and XSL.", "Components, forms, integrations and business rules with multidisciplinary teams."]'::jsonb, 'published', 2, 'Desenvolvimento e sustentação de portais corporativos.', 'Development and maintenance of corporate portals.', 'Desenvolvimento e sustentação de portais corporativos.', 'Development and maintenance of corporate portals.', array['Desenvolvimento e sustentação de portais corporativos.', 'Java, LumisXP, Hibernate, JavaScript, HTML, CSS e XSL.', 'Componentes, formulários, integrações e regras de negócio para equipes multidisciplinares.'], array['Development and maintenance of corporate portals.', 'Java, LumisXP, Hibernate, JavaScript, HTML, CSS and XSL.', 'Components, forms, integrations and business rules with multidisciplinary teams.'], null, null, false, null, null, null, array['Java', 'LumisXP', 'Hibernate', 'JavaScript', 'HTML', 'CSS', 'XSL'], 2, false, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000004', 'Event Horizon', 'Desenvolvedor Full Stack Freelancer e Fundador', 'Freelance Full Stack Developer and Founder', 'Desde 2018, em paralelo', 'Since 2018, alongside other work', '["Projetos independentes: sites, landing pages e sistemas personalizados.", "Levantamento de requisitos, frontend, backend, integrações, deploy e suporte pós-entrega."]'::jsonb, '["Independent projects: websites, landing pages and custom systems.", "Requirements discovery, frontend, backend, integrations, deployment and post-delivery support."]'::jsonb, 'published', 3, 'Projetos independentes: sites, landing pages e sistemas personalizados.', 'Independent projects: websites, landing pages and custom systems.', 'Projetos independentes: sites, landing pages e sistemas personalizados.', 'Independent projects: websites, landing pages and custom systems.', array['Projetos independentes: sites, landing pages e sistemas personalizados.', 'Levantamento de requisitos, frontend, backend, integrações, deploy e suporte pós-entrega.'], array['Independent projects: websites, landing pages and custom systems.', 'Requirements discovery, frontend, backend, integrations, deployment and post-delivery support.'], null, null, true, null, null, null, array[]::text[], 3, false, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null)
on conflict (id) do update set
  company = excluded.company, role_pt = excluded.role_pt, role_en = excluded.role_en, period_pt = excluded.period_pt, period_en = excluded.period_en, points_pt = excluded.points_pt, points_en = excluded.points_en, status = excluded.status, sort_order = excluded.sort_order, summary_pt = excluded.summary_pt, summary_en = excluded.summary_en, description_pt = excluded.description_pt, description_en = excluded.description_en, responsibilities_pt = excluded.responsibilities_pt, responsibilities_en = excluded.responsibilities_en, start_date = excluded.start_date, end_date = excluded.end_date, current = excluded.current, location_pt = excluded.location_pt, location_en = excluded.location_en, employment_type = excluded.employment_type, technologies = excluded.technologies, display_order = excluded.display_order, featured = excluded.featured, recruiter_visible = excluded.recruiter_visible, publication_status = excluded.publication_status, published_at = excluded.published_at, archived_at = excluded.archived_at;

insert into public.skills (
  id, category_pt, category_en, items, status, sort_order, name, name_pt, name_en, category,
  display_order, featured, recruiter_visible, publication_status, published_at, archived_at
) values
  ('00000000-0000-4000-8000-000000000101', 'Frontend & Mobile', 'Frontend and Mobile', 'React, React Native, Next.js, TypeScript, Tailwind CSS', 'published', 0, 'Frontend & Mobile', 'Frontend & Mobile', 'Frontend and Mobile', 'frontend_mobile', 0, true, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000102', 'Backend', 'Backend', 'Node.js, NestJS, REST, gRPC, Socket.IO, BullMQ', 'published', 1, 'Backend', 'Backend', 'Backend', 'backend', 1, true, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000103', 'Dados', 'Data', 'PostgreSQL, SQL Server, Prisma, Supabase, Redis', 'published', 2, 'Dados', 'Dados', 'Data', 'data', 2, false, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000104', 'Geolocalização', 'Geolocation', 'PostGIS, H3, deck.gl, Google Maps, Google Places', 'published', 3, 'Geolocalização', 'Geolocalização', 'Geolocation', 'geolocation', 3, false, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000105', 'Qualidade & Entrega', 'Quality and Delivery', 'Git, Docker, GitHub Actions, Jest, Cypress, Vercel, Sentry', 'published', 4, 'Qualidade & Entrega', 'Qualidade & Entrega', 'Quality and Delivery', 'quality_delivery', 4, false, true, 'published', '2026-08-05T00:00:00Z'::timestamptz, null)
on conflict (id) do update set
  category_pt = excluded.category_pt, category_en = excluded.category_en, items = excluded.items, status = excluded.status, sort_order = excluded.sort_order, name = excluded.name, name_pt = excluded.name_pt, name_en = excluded.name_en, category = excluded.category, display_order = excluded.display_order, featured = excluded.featured, recruiter_visible = excluded.recruiter_visible, publication_status = excluded.publication_status, published_at = excluded.published_at, archived_at = excluded.archived_at;

insert into public.education (
  id, institution, program_pt, program_en, detail_pt, detail_en, status, sort_order,
  course_pt, course_en, description_pt, description_en, start_date, end_date, current,
  display_order, publication_status, published_at, archived_at
) values
  ('00000000-0000-4000-8000-000000000201', 'Universidade Estácio', 'Bacharelado em Ciência da Computação', 'BSc in Computer Science', 'Fevereiro de 2025 - Fevereiro de 2028, previsão.', 'February 2025 - February 2028, expected.', 'published', 0, 'Bacharelado em Ciência da Computação', 'BSc in Computer Science', 'Fevereiro de 2025 - Fevereiro de 2028, previsão.', 'February 2025 - February 2028, expected.', null, null, false, 0, 'published', '2026-08-05T00:00:00Z'::timestamptz, null),
  ('00000000-0000-4000-8000-000000000202', 'Driven Education', 'Desenvolvimento de Software - Formação Intensiva', 'Software Development - Intensive Program', '1.200+ horas e 25+ projetos.', '1,200+ hours and 25+ projects.', 'published', 1, 'Desenvolvimento de Software - Formação Intensiva', 'Software Development - Intensive Program', '1.200+ horas e 25+ projetos.', '1,200+ hours and 25+ projects.', null, null, false, 1, 'published', '2026-08-05T00:00:00Z'::timestamptz, null)
on conflict (id) do update set
  institution = excluded.institution, program_pt = excluded.program_pt, program_en = excluded.program_en, detail_pt = excluded.detail_pt, detail_en = excluded.detail_en, status = excluded.status, sort_order = excluded.sort_order, course_pt = excluded.course_pt, course_en = excluded.course_en, description_pt = excluded.description_pt, description_en = excluded.description_en, start_date = excluded.start_date, end_date = excluded.end_date, current = excluded.current, display_order = excluded.display_order, publication_status = excluded.publication_status, published_at = excluded.published_at, archived_at = excluded.archived_at;
