insert into public.experiences (company, role_pt, role_en, period_pt, period_en, points_pt, points_en, status, sort_order)
values
  ('MARKTS', 'Desenvolvedor Full Stack Web & Mobile', 'Full Stack Web & Mobile Developer', 'Junho de 2025 - Atual', 'June 2025 - Present', '["Aplicações Web, Android e iOS entre múltiplos frontends e microserviços.", "React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ e Prisma.", "Mapas e análise geográfica com H3, deck.gl e Google Maps.", "Fluxos com regras de negócio, máquinas de estado e operação móvel sob conectividade instável."]', '["Web, Android and iOS applications across multiple frontends and microservices.", "React, React Native, TypeScript, NestJS, REST, gRPC, Socket.IO, Redis, BullMQ and Prisma.", "Maps and geographic analysis with H3, deck.gl and Google Maps.", "Business-rule flows, state machines and mobile operation under unreliable connectivity."]', 'published', 0),
  ('SALB - Indústria Cerealista', 'Desenvolvedor Full Stack', 'Full Stack Developer', 'Dezembro de 2024 - Maio de 2025', 'December 2024 - May 2025', '["Site institucional e catálogo de produtos.", "QR Codes em produtos, estoque, etiquetas e integrações de cadastro.", "Integração com roteirização de entregas usando Next.js, TypeScript, Prisma e PostgreSQL."]', '["Institutional website and product catalog.", "Product QR codes, inventory, labels and product-record integrations.", "Delivery-routing integration using Next.js, TypeScript, Prisma and PostgreSQL."]', 'published', 1),
  ('Lumis', 'Desenvolvedor Web/Java', 'Web/Java Developer', 'Junho de 2022 - Dezembro de 2023', 'June 2022 - December 2023', '["Desenvolvimento e sustentação de portais corporativos.", "Java, LumisXP, Hibernate, JavaScript, HTML, CSS e XSL.", "Componentes, formulários, integrações e regras de negócio para equipes multidisciplinares."]', '["Development and maintenance of corporate portals.", "Java, LumisXP, Hibernate, JavaScript, HTML, CSS and XSL.", "Components, forms, integrations and business rules with multidisciplinary teams."]', 'published', 2),
  ('Event Horizon', 'Desenvolvedor Full Stack Freelancer e Fundador', 'Freelance Full Stack Developer and Founder', 'Desde 2018, em paralelo', 'Since 2018, alongside other work', '["Projetos independentes: sites, landing pages e sistemas personalizados.", "Levantamento de requisitos, frontend, backend, integrações, deploy e suporte pós-entrega."]', '["Independent projects: websites, landing pages and custom systems.", "Requirements discovery, frontend, backend, integrations, deployment and post-delivery support."]', 'published', 3);

insert into public.skills (category_pt, category_en, items, status, sort_order)
values
  ('Frontend & Mobile', 'Frontend and Mobile', 'React, React Native, Next.js, TypeScript, Tailwind CSS', 'published', 0),
  ('Backend', 'Backend', 'Node.js, NestJS, REST, gRPC, Socket.IO, BullMQ', 'published', 1),
  ('Dados', 'Data', 'PostgreSQL, SQL Server, Prisma, Supabase, Redis', 'published', 2),
  ('Geolocalização', 'Geolocation', 'PostGIS, H3, deck.gl, Google Maps, Google Places', 'published', 3),
  ('Qualidade & Entrega', 'Quality and Delivery', 'Git, Docker, GitHub Actions, Jest, Cypress, Vercel, Sentry', 'published', 4);
