"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";

const contactUpdate = z.object({ id: z.string().uuid(), status: z.enum(["new", "reviewing", "contacted", "opportunity", "interview", "proposal", "hired", "closed", "spam"]).optional(), priority: z.enum(["low", "normal", "high", "urgent"]).optional(), nextActionAt: z.string().max(40).optional(), note: z.string().trim().min(1).max(5000).optional() });
export async function updateContact(formData: FormData) { const admin = await requireAdmin(); const parsed = contactUpdate.safeParse(Object.fromEntries(formData)); if (!parsed.success) return; const { id, note, nextActionAt, ...changes } = parsed.data; const supabase = await createClient(); if (note) await supabase.from("contact_notes").insert({ contact_id: id, author_id: admin.id, content: note }); if (Object.keys(changes).length || nextActionAt !== undefined) await supabase.from("contact_submissions").update({ ...changes, next_action_at: nextActionAt || null, updated_at: new Date().toISOString() }).eq("id", id); await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "contact", entity_id: id, action: note ? "note_added" : "updated", changes: changes }); revalidatePath("/admin"); revalidatePath("/admin/crm/contacts"); revalidatePath(`/admin/crm/contacts/${id}`); }
const statuses = ["prospect", "applied", "recruiter_contact", "screening", "technical_interview", "final_interview", "offer", "hired", "rejected", "withdrawn"] as const;
const blank = z.preprocess(value => value === "" ? undefined : value, z.string().optional());
const optionalNumber = z.preprocess(value => value === "" ? undefined : value, z.coerce.number().nonnegative().optional());
const optionalDate = z.preprocess(value => value === "" ? undefined : value, z.string().refine(value => !Number.isNaN(Date.parse(value))).optional());
const opportunity = z.object({ id: blank.pipe(z.string().uuid().optional()), title: z.string().trim().min(2).max(180), company_name: blank.pipe(z.string().trim().max(180).optional()), employment_type: blank.pipe(z.string().trim().max(80).optional()), work_model: blank.pipe(z.string().trim().max(80).optional()), salary_min: optionalNumber, salary_max: optionalNumber, currency: z.string().trim().length(3).default("BRL"), status: z.enum(statuses), contact_id: blank.pipe(z.string().uuid().optional()), source: blank.pipe(z.string().trim().max(180).optional()), job_url: blank.pipe(z.url().optional()), next_action_at: optionalDate, interview_at: optionalDate, closed_at: optionalDate, notes: blank.pipe(z.string().max(5000).optional()) }).refine(x => x.salary_max === undefined || x.salary_min === undefined || x.salary_max >= x.salary_min, { message: "Faixa salarial inválida", path: ["salary_max"] });
export async function saveOpportunity(formData: FormData) { const admin = await requireAdmin(); const parsed = opportunity.safeParse(Object.fromEntries(formData)); if (!parsed.success) return; const { id, ...values } = parsed.data; const supabase = await createClient(); if (values.contact_id) { const contact = await supabase.from("contact_submissions").select("id").eq("id", values.contact_id).maybeSingle(); if (!contact.data) return; } const data = { ...values, contact_id: values.contact_id || null, next_action_at: values.next_action_at || null, interview_at: values.interview_at || null, closed_at: values.closed_at || null }; const result = id ? await supabase.from("opportunities").update(data).eq("id", id).select("id").single() : await supabase.from("opportunities").insert(data).select("id").single(); if (result.error || !result.data) return; await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "opportunity", entity_id: result.data.id, action: id ? "updated" : "created", changes: { status: data.status } }); revalidatePath("/admin"); revalidatePath("/admin/crm/opportunities"); revalidatePath(`/admin/crm/opportunities/${result.data.id}`); }
export async function convertContact(formData: FormData) { const admin = await requireAdmin(); const id = z.string().uuid().safeParse(formData.get("id")); if (!id.success) return; const supabase = await createClient(); const { data: contact } = await supabase.from("contact_submissions").select("company, subject").eq("id", id.data).single(); const result = await supabase.from("opportunities").insert({ contact_id: id.data, title: contact?.subject || "Oportunidade", company_name: contact?.company || null, status: "prospect" }).select("id").single(); if (result.error || !result.data) return; await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "contact", entity_id: id.data, action: "converted", changes: {} }); revalidatePath("/admin/crm/contacts"); }
