"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";

const contactUpdate = z.object({ id: z.string().uuid(), status: z.enum(["new", "reviewing", "contacted", "opportunity", "interview", "proposal", "hired", "closed", "spam"]).optional(), priority: z.enum(["low", "normal", "high", "urgent"]).optional(), nextActionAt: z.string().max(40).optional(), note: z.string().trim().min(1).max(5000).optional() });
export async function updateContact(formData: FormData) { const admin = await requireAdmin(); const parsed = contactUpdate.safeParse(Object.fromEntries(formData)); if (!parsed.success) return; const { id, note, nextActionAt, ...changes } = parsed.data; const supabase = await createClient(); if (note) await supabase.from("contact_notes").insert({ contact_id: id, author_id: admin.id, content: note }); if (Object.keys(changes).length || nextActionAt !== undefined) await supabase.from("contact_submissions").update({ ...changes, next_action_at: nextActionAt || null, updated_at: new Date().toISOString() }).eq("id", id); await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "contact", entity_id: id, action: note ? "note_added" : "updated", changes: changes }); revalidatePath("/admin"); revalidatePath("/admin/crm/contacts"); revalidatePath(`/admin/crm/contacts/${id}`); }
const opportunity = z.object({ id: z.string().uuid().optional(), title: z.string().trim().min(2).max(180), company_name: z.string().trim().max(180).optional(), status: z.enum(["prospect", "applied", "recruiter_contact", "screening", "technical_interview", "final_interview", "offer", "hired", "rejected", "withdrawn"]), contact_id: z.string().uuid().optional(), next_action_at: z.string().max(40).optional(), interview_at: z.string().max(40).optional(), notes: z.string().max(5000).optional() });
export async function saveOpportunity(formData: FormData) { const admin = await requireAdmin(); const parsed = opportunity.safeParse(Object.fromEntries(formData)); if (!parsed.success) return; const { id, ...values } = parsed.data; const supabase = await createClient(); const data = { ...values, contact_id: values.contact_id || null, next_action_at: values.next_action_at || null, interview_at: values.interview_at || null }; const result = id ? await supabase.from("opportunities").update(data).eq("id", id).select("id").single() : await supabase.from("opportunities").insert(data).select("id").single(); if (result.error || !result.data) return; await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "opportunity", entity_id: result.data.id, action: id ? "updated" : "created", changes: { status: data.status } }); revalidatePath("/admin"); revalidatePath("/admin/crm/opportunities"); }
export async function convertContact(formData: FormData) { const admin = await requireAdmin(); const id = z.string().uuid().safeParse(formData.get("id")); if (!id.success) return; const supabase = await createClient(); const { data: contact } = await supabase.from("contact_submissions").select("company, subject").eq("id", id.data).single(); const result = await supabase.from("opportunities").insert({ contact_id: id.data, title: contact?.subject || "Oportunidade", company_name: contact?.company || null, status: "prospect" }).select("id").single(); if (result.error || !result.data) return; await supabase.from("audit_logs").insert({ actor_id: admin.id, entity_type: "contact", entity_id: id.data, action: "converted", changes: {} }); revalidatePath("/admin/crm/contacts"); }
