import { createHash } from "crypto";
import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";

const schema = z.object({ name: z.string().trim().min(2).max(80), email: z.string().trim().email().max(120), company: z.string().trim().max(120).optional().or(z.literal("")), subject: z.string().trim().max(180).optional().or(z.literal("")), message: z.string().trim().min(10).max(2000), sourcePath: z.string().startsWith("/").max(300).optional(), utmSource: z.string().max(120).optional(), utmMedium: z.string().max(120).optional(), utmCampaign: z.string().max(120).optional(), honeypot: z.string().max(0).optional(), turnstileToken: z.string().optional() });
const attempts = new Map<string, { count: number; reset: number }>();
async function verifyTurnstile(token?: string) { if (!process.env.TURNSTILE_SECRET_KEY) return true; if (!token) return false; const body = new URLSearchParams({ secret: process.env.TURNSTILE_SECRET_KEY, response: token }); const response = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", { method: "POST", body }); const result = await response.json() as { success?: boolean }; return result.success === true; }
export async function POST(request: NextRequest) { const ip = request.headers.get("x-forwarded-for")?.split(",")[0] ?? "unknown"; const key = createHash("sha256").update(ip).digest("hex"); const now = Date.now(); const entry = attempts.get(key); if (entry && entry.reset > now && entry.count >= 5) return NextResponse.json({ error: "Unable to send message." }, { status: 429 }); if (!entry || entry.reset <= now) attempts.set(key, { count: 1, reset: now + 60_000 }); else entry.count += 1; const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success || parsed.data.honeypot || !(await verifyTurnstile(parsed.data.turnstileToken))) return NextResponse.json({ error: "Unable to send message." }, { status: 400 }); try { await createAdminClient().from("contact_submissions").insert({ name: parsed.data.name, email: parsed.data.email, company: parsed.data.company || null, subject: parsed.data.subject || null, message: parsed.data.message, source_path: parsed.data.sourcePath ?? null, utm_source: parsed.data.utmSource ?? null, utm_medium: parsed.data.utmMedium ?? null, utm_campaign: parsed.data.utmCampaign ?? null, referrer: request.headers.get("referer")?.slice(0, 500) ?? null }); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "Unable to send message." }, { status: 500 }); } }
