"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Command, Menu, Moon, Sun, X } from "lucide-react";
import type { Locale } from "@/content/data";
import { track } from "@/lib/analytics";
type Props = { children: React.ReactNode; locale: Locale; theme: "light" | "dark"; recruiter: boolean };
const nav = [["/", "Início", "Home"], ["/experiencia", "Experiência", "Experience"], ["/projetos", "Projetos", "Projects"], ["/sobre", "Sobre", "About"], ["/contato", "Contato", "Contact"]]; const setCookie = (name: string, value: string) => { document.cookie = `${name}=${value};path=/;max-age=31536000;samesite=lax`; };
export function ClientShell({ children, locale, theme, recruiter: initialRecruiter }: Props) { const [recruiter, setRecruiter] = useState(initialRecruiter); const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); useEffect(() => { const nodes = [document.getElementById("site-header"), document.getElementById("site-content")]; nodes.forEach(node => node?.toggleAttribute("inert", open)); return () => nodes.forEach(node => node?.removeAttribute("inert")); }, [open]); const changeLocale = () => { const next = locale === "pt" ? "en" : "pt"; setCookie("juan-locale", next); localStorage.setItem("juan-locale", next); track("language_changed", { locale: next }); window.location.reload(); }; const changeTheme = () => { const next = theme === "light" ? "dark" : "light"; document.documentElement.dataset.theme = next; setCookie("juan-theme", next); localStorage.setItem("juan-theme", next); window.location.reload(); }; const changeRecruiter = () => { const next = !recruiter; setRecruiter(next); setCookie("juan-recruiter", String(next)); if (next) track("recruiter_mode_enabled"); }; const close = () => { setOpen(false); requestAnimationFrame(() => trigger.current?.focus()); }; return <div data-recruiter={recruiter ? "true" : "false"}><header id="site-header" className="sticky top-0 z-40 border-b border-[var(--line)] bg-[color:var(--bg)]/90 backdrop-blur"><div className="shell flex h-16 items-center justify-between gap-3"><Link href="/" className="font-bold">JUAN<span className="text-[var(--brand)]">.SUED</span></Link><nav className="hidden gap-5 text-sm md:flex" aria-label={locale === "pt" ? "Principal" : "Primary"}>{nav.map(([href, pt, en]) => <Link key={href} href={href}>{locale === "pt" ? pt : en}</Link>)}</nav><div className="flex gap-1"><button onClick={changeLocale} aria-label={locale === "pt" ? "Idioma" : "Language"}>{locale.toUpperCase()}</button><button onClick={changeTheme} aria-label={locale === "pt" ? "Tema" : "Theme"}>{theme === "dark" ? <Sun size={18}/> : <Moon size={18}/>}</button><button onClick={changeRecruiter} className="hidden sm:block">{locale === "pt" ? "Modo Recrutador" : "Recruiter mode"}</button><button ref={trigger} onClick={() => setOpen(true)} aria-label={locale === "pt" ? "Menu de comandos" : "Command menu"}><Command size={18}/></button><button className="md:hidden" aria-label="Menu"><Menu/></button></div></div></header><div id="site-content">{recruiter && <div className="shell mt-4 rounded-lg bg-[var(--brand-soft)] p-3 font-bold">{locale === "pt" ? "Modo Recrutador - Visão em 60 segundos" : "Recruiter Mode - 60-second view"}</div>}{children}</div>{open && <CommandMenu locale={locale} close={close}/>}</div>; }
function CommandMenu({ locale, close }: { locale: Locale; close: () => void }) { const ref = useRef<HTMLDivElement>(null); const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { closeRef.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key === "Tab") { const nodes = ref.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled])'); if (!nodes?.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", key); return () => document.removeEventListener("keydown", key); }, [close]); return <div className="fixed inset-0 z-50 bg-black/40 p-4 pt-16" onMouseDown={close}><div ref={ref} role="dialog" aria-modal="true" aria-labelledby="command-title" className="mx-auto w-full max-w-xl rounded-xl bg-[var(--surface)] p-3" onMouseDown={event => event.stopPropagation()}><div className="flex justify-between p-3"><h2 id="command-title">{locale === "pt" ? "Menu de comandos" : "Command menu"}</h2><button ref={closeRef} onClick={close}>{locale === "pt" ? "Fechar" : "Close"}</button></div><div className="grid">{[[locale === "pt" ? "Ver experiência" : "View experience", "/experiencia"], ["BikerWay", "/projetos/bikerway"], [locale === "pt" ? "Explorar estudos de caso" : "Explore case studies", "/projetos"]].map(([name, href]) => <Link key={href} href={href} onClick={close} className="p-3">{name}</Link>)}<a download href="/curriculos/juan-sued-cv-ats.pdf" className="p-3">{locale === "pt" ? "Baixar currículo ATS" : "Download ATS resume"}</a><a download href="/curriculos/juan-sued-cv-visual.pdf" className="p-3">{locale === "pt" ? "Baixar currículo visual" : "Download visual resume"}</a></div></div></div>; }
